# ============================================================
# Información del Proyecto
# ============================================================
serenity.project.name=Compra de Productos en Linea - Demoblaze
serenity.test.root=com.demoblaze

# Driver Configuration
webdriver.driver=chrome
webdriver.base.url=https://www.demoblaze.com/index.html
webdriver.wait.for.timeout=10000

# ============================================================
# Opciones del Browser
# ============================================================
chrome.switches=--start-maximized

# Reporting and Screenshots
serenity.take.screenshots=FOR_FAILURES
serenity.console.headings=normal
serenity.reports.show.step.details=true
serenity.report.encoding=UTF-8



