serenity {
  project.name = "Demoblaze Automation"
  take.screenshots = AFTER_EACH_STEP
  reports.show.step.details = true
  test.root = "com.demoblaze"
  report.encoding = "UTF-8"
}

webdriver {
  driver = chrome
  autodownload = true

  capabilities {
    browserName = "chrome"
    acceptInsecureCerts = true


    "goog:chromeOptions" {
      args = [
        "--no-sandbox",
        "--disable-dev-shm-usage",
        "--disable-gpu",
        "--start-maximized",
        "--disable-popup-blocking",
        "--disable-notifications",
        "--disable-infobars",
        "--disable-extensions"
        # Descomenta la siguiente línea para ejecutar en modo headless
        # "--headless=new"
      ]
    }
  }
}

environments {
  default {
    webdriver.base.url = "https://www.demoblaze.com"
  }
  staging {
    webdriver.base.url = "https://staging.demoblaze.com"
  }
  prod {
    webdriver.base.url = "https://www.demoblaze.com"
  }
}
